### ISSUE TITLE
Add separate branch with solutions

### ISSUE THREAD

**Issue by AndrewLosseff** [lmammino/advent-of-solidjs#4]
Could we add separate branch with solutions for problems? (For ex. `solutions`)
And keep main one only for problem description.

**Comment by lmammino** [comment]
Hello Andrew, thanks a lot for the suggestion!

This is a good suggestion but I am not expecting people to do the challenges off of this repo (I hope they'd go through adventofvue.com instead).

So it's just much easier for me to keep everything in the main branch rather than having to manage multiple branches...

I hope this makes sense to you
